targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            # domain
            - lib/domain/**.dart
            # service
            - lib/service/model/**.dart
            - lib/service/base/model/**.dart
      json_serializable:
        options:
          field_rename: snake
