/// Flutter icons WebIconApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WebIconApp
///      fonts:
///       - asset: fonts/WebIconApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class WebIconApp {
  WebIconApp._();

  static const _kFontFam = 'WebIconApp';
  static const String? _kFontPkg = null;

  static const IconData keyboardarrowdown = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xeaee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_border = IconData(0xeb15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus_squared = IconData(0xf0d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus = IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
